<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<UseWPF>true</UseWPF>
		<EnableWindowsTargeting>true</EnableWindowsTargeting>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<Version>1.0.0</Version>
		<AssemblyVersion>1.0.0.0</AssemblyVersion>
		<FileVersion>1.0.0.0</FileVersion>
		<InformationalVersion>1.0.0</InformationalVersion>

		<ApplicationIcon>Assets\Icons\leazi-app.ico</ApplicationIcon>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.3.2" />

		<PackageReference Include="MaterialDesignThemes" Version="5.1.0" />

		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.30" />

		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.30">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>

		<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.30" />

		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />

		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.2" />

		<PackageReference Include="QuestPDF" Version="2026.7.3" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\LeaziEnergiaSolar.Application\LeaziEnergiaSolar.Application.csproj" />

		<ProjectReference Include="..\LeaziEnergiaSolar.Infrastructure\LeaziEnergiaSolar.Infrastructure.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Resource Include="Assets\Images\logo-leazi.png" />
		<Resource Include="Assets\Icons\leazi-app.ico" />
	</ItemGroup>

	<Target Name="CopyReportLogo"
			AfterTargets="Build">

		<MakeDir
			Directories="$(OutDir)Assets\Images" />

		<Copy
			SourceFiles="$(MSBuildProjectDirectory)\Assets\Images\logo-leazi.png"
			DestinationFiles="$(OutDir)Assets\Images\logo-leazi.png"
			SkipUnchangedFiles="true" />

	</Target>
</Project>